# Generated by Django 4.2.6 on 2023-10-06 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rentbook',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='LibUser',
        ),
        migrations.DeleteModel(
            name='RentBook',
        ),
    ]
